### ISSUE TITLE
Enhanced ASL Code with PMEX

### ISSUE THREAD

**Issue by StarPatroller** [TheGag96/pm-hax#1]
I am unable to get the enhanced ASL code to work with Project M + BrawlEx. I've tried compiling the code both with and without the changes mentioned at line 185 without any success. This isn't just an issue with STGEX stages; I can't load alts on any of the default stages either. I'm testing this on Dolphin if it matters.

**Comment by TheGag96** [comment]
Sorry I'm a month late to this! I'll take a look. It may just be that I need to find another address to use for the CSS slot.

**Comment by TheGag96** [comment]
Found the issue. My latest push should fix it. Apparently, vanilla PM will only care about the required buttons being pressed and ignore all other buttons. For Legacy XP, we had it set up so that you could only get to the alt if ONLY the buttons in the ASL data were pressed. I included the option for both behaviors now.
